"""Create demo workload tables

Revision ID: 4eb6e144f9a4
Revises: 0f3346acf2ee
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "4eb6e144f9a4"
down_revision: str | None = "0f3346acf2ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "demo_changes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("service", sa.String(length=40), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column(
            "changes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_demo_changes_timestamp"), "demo_changes", ["timestamp"], unique=False)
    op.create_table(
        "demo_config",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column(
            "value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "demo_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_demo_jobs_status"), "demo_jobs", ["status"], unique=False)
    op.create_table(
        "demo_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("service", sa.String(length=40), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_demo_logs_service"), "demo_logs", ["service"], unique=False)
    op.create_index(op.f("ix_demo_logs_timestamp"), "demo_logs", ["timestamp"], unique=False)
    op.create_table(
        "demo_worker_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("processed", sa.Integer(), nullable=False),
        sa.Column("last_success", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("demo_worker_state")
    op.drop_index(op.f("ix_demo_logs_timestamp"), table_name="demo_logs")
    op.drop_index(op.f("ix_demo_logs_service"), table_name="demo_logs")
    op.drop_table("demo_logs")
    op.drop_index(op.f("ix_demo_jobs_status"), table_name="demo_jobs")
    op.drop_table("demo_jobs")
    op.drop_table("demo_config")
    op.drop_index(op.f("ix_demo_changes_timestamp"), table_name="demo_changes")
    op.drop_table("demo_changes")
    # ### end Alembic commands ###
